### ISSUE TITLE
Tool monitoring not working in virtualbox.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo-machine#20]

**Comment by jmchilton** [comment]
Seems to have something to do with shared filesystem - tool monitoring of other directories in that setup works fine. Probably this issue discovered by @kellrott (https://www.virtualbox.org/ticket/10660?cversion=0&cnum_hist=1).

Using `from watchdog.observers.polling import PollingObserver` Instead of using `from watchdog.observers import Observer` seems to fix the problem. Just need to get that into Galaxy somehow.

**Comment by kellrott** [comment]
I'm not sure if the tool monitoring is working in the docker image either. Maybe the same issue?

**Comment by jmchilton** [comment]
Just pulled latest from hub and it seemed to work for me. You have refresh the browser for the tool to show up - did you try that? Also it appears as though the IDE problem was fixed.

As Galaxy is currently homeless I am doing a build against the following commit:

https://bitbucket.org/jmchilton/galaxy-central-fork-1/commits/19ab1cae127886c06058c09525796140057f0b2b

which adds a new option to watch tools based on polling.

https://github.com/galaxyproject/planemo-machine/compare/watch_test?expand=1

I'll let you know if that build works any better.

**Comment by kellrott** [comment]
Still having a problem. I start the instance with:
docker run -p 8010:80 -v /data/tools:/opt/galaxy/tools planemo/box

Then I log into the IDE and open a terminal and type:
planemo project_init dpc
cd dpc/  
planemo tool_init --id dpc                                                                                                        

Galaxy logs an event:
watchdog.observers.inotify_buffer DEBUG 2015-02-22 06:24:08,599 in-event <InotifyEvent: src_path=/opt/galaxy/tools/dpc, wd=1, mask=IN_CREATE|IN_ISDIR, cookie=0, name=dpc>  

But I don't see any other logging info about tool loading or any other events related to dpc. When I make changes to the file, I don't see any other logs about the watchdog, even when I made changes to the XML file. And the tool never appeared in the browser, even after refreshing the screen.

**Comment by jmchilton** [comment]
project_init doesn't really do anything when used that way and not sure the recursive thing works for "new" directories. Just do a tool_init from tools directly and it should work.

**Comment by kellrott** [comment]
Ok that was the different. I've been try to create new project folders in /opt/galaxy/tools or doing git clones of existing tools into the directory. 
If its not doing recursive searches on newly created directories, that way my tools were never being picked up.
I ran 'planemo tool_init' in the base directory, and it picked up the tool correctly.

We should make sure to note this in the manual.

**Comment by jmchilton** [comment]
Indeed - we should also get recursive addition of directories working - I think it does work for scanning tools right.

Okay - new box - fixes tool monitoring though it has become very expensive to run the machine on my laptop :(.
https://images.galaxyproject.org/planemo/20150222.box

Want to give a shot and let me know if you have any feedback.

Tonight if I have time I will try another pass with following changes -
- Just one Galaxy process (instead of separate web and handlers processes)
- Fewer tool directories to monitor (trim up the tool panel)
- Installing a older version of codebox (0.8.1 instead 0.8.3) - the terminal on the new version seems hosed (what do you think?). It could just be everything is very bogged down in my current setup.

**Comment by jmchilton** [comment]
Made those changes and I like them I think - new box available at following locations:

https://images.galaxyproject.org/planemo/20150222.1.box
https://images.galaxyproject.org/planemo/latest.box
